version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ccc_postgres
    environment:
      POSTGRES_DB: culture_connect
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: securepassword
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: ccc_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    container_name: ccc_backend
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://app_user:securepassword@db:5432/culture_connect
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_jwt_secret_key_here
      - SESSION_SECRET=your_session_secret_key_here
      - NODE_ENV=development
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  postgres_data:
  redis_data:
